
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "CaskaydiaMono NFM"
# family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
family = "CaskaydiaMono NFM"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "CaskaydiaMono NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaMono NFM"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
